module.exports = app =>{
    app.post('/cadUser', app.api.usuario.cadUser.saveUser)
    app.post('/cadEmpresa', app.api.empresa.cadEmpresa.saveEmpresa)
    app.post('/signinUser', app.api.authUser.signinUser)
    app.post('/signinEmpresa', app.api.authEmpresa.signinEmpresa)
    app.post('/resetPswUser', app.api.resetPswUser.newPassword)
    app.post('/requestCode', app.api.empresa.generateCode.newCode)
    app.post('/saveService', app.api.empresa.cadServico.saveServico)
    app.get('/getService/:token', app.api.empresa.getService.getService)    
    app.delete('/deleteService/:id', app.api.empresa.deleteService.deleteService)
    app.put('/updateService/:id', app.api.empresa.updateService.updateService)    
    app.get('/getEmpresas/:speciality', app.api.usuario.getEmpresa.getEmpresa)
    app.post('/refresh', app.api.usuario.refresh.refresh)
    app.get('/validateCode/:code', app.api.validateCode.validateCode)
    app.put('/resetPassword', app.api.resetPswEmp.newPassword)
    app.post('/requestCodeMobile', app.api.usuario.generateCodeUser.newCode)
    app.post('/favorites', app.api.usuario.favorito.saveFavorito)
    app.get('/companie/:idEmpresa', app.api.usuario.getInfoEmpresa.getInfo)
    app.delete('/deleteFavorite', app.api.usuario.deleteFavorite.deleteFavorite)
    app.get('/getServices/:idEmpresa', app.api.usuario.getServices.getServices)
    app.get('/getFavorites/:idEmpresa', app.api.usuario.getFavorite.getFavorite)
    app.get('/getHoursService/:idEmpresa/:idServico/:dataServico', app.api.usuario.getHoursService.getHoursService)
    app.post('/saveSchedule', app.api.usuario.saveSchedule.saveSchedule)
    app.get('/getSchedule', app.api.usuario.getSchedule.getSchedule)
    
    app.get('/getListFavorites', app.api.usuario.getFavorites.getFavorites)
    app.delete('/deleteSchedule/:idAgenda', app.api.usuario.deleteSchedule.deleteSchedule)
}